In [1]:
import sklearn
import pandas as pd
import numpy as np


In [2]:
df = pd.read_csv('data/CleanedData.csv')

In [3]:
df.head()

subject                                   transformed text
0        1  donald trump wish american happi new year leav...
1        1  hous intellig committe chairman devin nune go ...
2        1  friday reveal former milwauke sheriff david cl...
3        1  christma day donald trump announc would back w...
4        1  pope franci use annual christma day messag reb...

In [4]:
df.shape

(43244, 2)

In [5]:
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
cv = CountVectorizer()
tfidf = TfidfVectorizer(max_features=2000)

In [6]:
X= tfidf.fit_transform(df['transformed text']).toarray()
y= df['subject'].values

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test= train_test_split(X,y,test_size=0.2,random_state=42)

In [8]:
from sklearn.naive_bayes import GaussianNB,MultinomialNB,BernoulliNB
from sklearn.metrics import accuracy_score,confusion_matrix,precision_score
gnb = GaussianNB()
bnb= BernoulliNB()
mnb= MultinomialNB()

In [9]:
gnb.fit(X_train,y_train)
y_pred1= gnb.predict(X_test)
print("accuracy_score =",accuracy_score(y_test,y_pred1))
print("Confusion Matrix:\n",confusion_matrix(y_test,y_pred1))
print("weighted precision_score =" ,precision_score(y_test,y_pred1, average = 'weighted'))

accuracy_score = 0.6160249739854319
Confusion Matrix:
 [[ 112   33   18   67   25   18]
 [ 115 1391   75  213   70   10]
 [   4    8  124    7    9    2]
 [ 189  164   63  377   33   21]
 [ 474  429  187  572 1461  373]
 [  24    8   12   28   70 1863]]
weighted precision_score = 0.7288051071572783


In [10]:
mnb.fit(X_train,y_train)
y_pred2= mnb.predict(X_test)
print("accuracy_score =",accuracy_score(y_test,y_pred2))
print("Confusion Matrix:\n",confusion_matrix(y_test,y_pred2))
print("weighted precision_score =" ,precision_score(y_test,y_pred2, average = 'weighted'))

accuracy_score = 0.7203144872239565
Confusion Matrix:
 [[   3   33    0   37  186   14]
 [   0 1501    0   45  321    7]
 [   0   10   77   10   45   12]
 [   0  238    0  221  364   24]
 [   0  408    0  226 2609  253]
 [   0    3    0    7  176 1819]]
weighted precision_score = 0.7203185797401375


In [11]:
bnb.fit(X_train,y_train)
y_pred3= bnb.predict(X_test)
print("accuracy_score =",accuracy_score(y_test,y_pred3))
print("Confusion Matrix:\n",confusion_matrix(y_test,y_pred3))
print("weighted precision_score =" ,precision_score(y_test,y_pred3, average = 'weighted'))

accuracy_score = 0.7136085096542953
Confusion Matrix:
 [[  95    7   31  100   35    5]
 [  43 1646   27   90   67    1]
 [  10    0   75   58    7    4]
 [  89   51   78  558   65    6]
 [ 176   88  189  789 1955  299]
 [   7    0   69   18   68 1843]]
weighted precision_score = 0.800549735723183


## Bernoulli Naive Bayes gives the best accuracy, so we will proceed with it