In [1]:
import sklearn
import pandas as pd
import numpy as np


In [2]:
df = pd.read_csv('data/CleanedData.csv')

In [3]:
df.head()

subject                                   transformed text
0        1  donald trump wish american happi new year leav...
1        1  hous intellig committe chairman devin nune go ...
2        1  friday reveal former milwauke sheriff david cl...
3        1  christma day donald trump announc would back w...
4        1  pope franci use annual christma day messag reb...

In [4]:
df.shape

(43125, 2)

In [5]:
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
cv = CountVectorizer()
tfidf = TfidfVectorizer(max_features=2000)

In [6]:
df.isnull().sum()

subject             0
transformed text    0
dtype: int64

In [7]:
X= tfidf.fit_transform(df['transformed text']).toarray()
y= df['subject'].values

In [8]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test= train_test_split(X,y,test_size=0.2,random_state=42)

In [9]:
from sklearn.naive_bayes import GaussianNB,MultinomialNB,BernoulliNB
from sklearn.metrics import accuracy_score,confusion_matrix,precision_score
gnb = GaussianNB()
bnb= BernoulliNB()
mnb= MultinomialNB()

In [10]:
gnb.fit(X_train,y_train)
y_pred1= gnb.predict(X_test)
print("accuracy_score =",accuracy_score(y_test,y_pred1))
print("Confusion Matrix:\n",confusion_matrix(y_test,y_pred1))
print("weighted precision_score =" ,precision_score(y_test,y_pred1, average = 'weighted'))

accuracy_score = 0.6041739130434782
Confusion Matrix:
 [[ 126   39   23   58   26   15]
 [ 151 1258   94  258  100   15]
 [   8    9  118   14    7    9]
 [ 166  183   40  369   51   26]
 [ 416  419  153  604 1486  397]
 [  23    7    8   25   70 1854]]
weighted precision_score = 0.7081787022144945


In [11]:
mnb.fit(X_train,y_train)
y_pred2= mnb.predict(X_test)
print("accuracy_score =",accuracy_score(y_test,y_pred2))
print("Confusion Matrix:\n",confusion_matrix(y_test,y_pred2))
print("weighted precision_score =" ,precision_score(y_test,y_pred2, average = 'weighted'))

accuracy_score = 0.694376811594203
Confusion Matrix:
 [[   2   47    0   30  195   13]
 [   0 1385    0   65  417    9]
 [   1   23   55   20   52   14]
 [   0  270    0  196  334   35]
 [   1  432    1  211 2570  260]
 [   0    3    0   10  193 1781]]
weighted precision_score = 0.6801439615293031


In [12]:
bnb.fit(X_train,y_train)
y_pred3= bnb.predict(X_test)
print("accuracy_score =",accuracy_score(y_test,y_pred3))
print("Confusion Matrix:\n",confusion_matrix(y_test,y_pred3))
print("weighted precision_score =" ,precision_score(y_test,y_pred3, average = 'weighted'))

accuracy_score = 0.6764057971014493
Confusion Matrix:
 [[  98   22   33   97   32    5]
 [  61 1442   42  206  124    1]
 [  18    5   84   53    3    2]
 [  86  121   74  483   60   11]
 [ 153  188  211  716 1899  308]
 [  12    2   54   17   74 1828]]
weighted precision_score = 0.7612601574292666


## Bernoulli Naive Bayes gives the best accuracy, so we will proceed with it