In [1]:
import sklearn
import pandas as pd
import numpy as np


In [3]:
df = pd.read_csv('data/cleaned_text.csv')

In [4]:
df.head()

category                                   transformed text
0         4  tv futur hand viewer home theatr system plasma...
1         0  worldcom boss leav book alon former worldcom b...
2         3  tiger wari farrel gambl leicest say rush make ...
3         3  yead face newcastl fa cup premiership side new...
4         1  ocean twelv raid box offic ocean twelv crime c...

In [5]:
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
cv = CountVectorizer()
tfidf = TfidfVectorizer(max_features=3000)

In [6]:
X= tfidf.fit_transform(df['transformed text']).toarray()
y= df['category'].values

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test= train_test_split(X,y,test_size=0.2,random_state=42)

In [8]:
from sklearn.naive_bayes import GaussianNB,MultinomialNB,BernoulliNB
from sklearn.metrics import accuracy_score,confusion_matrix,precision_score
gnb = GaussianNB()
bnb= BernoulliNB()
mnb= MultinomialNB()

In [15]:
gnb.fit(X_train,y_train)
y_pred1= gnb.predict(X_test)
print("accuracy_score",accuracy_score(y_test,y_pred1))
print("Confusion Matrix:\n",confusion_matrix(y_test,y_pred1))
print("weighted precision_score -" ,precision_score(y_test,y_pred1, average = 'weighted'))

accuracy_score 0.9084507042253521
Confusion Matrix:
 [[ 79   3   5   0   9]
 [  0  61   2   0   5]
 [  4   3  76   0   0]
 [  0   1   0 107   1]
 [  4   1   1   0  64]]
weighted precision_score - 0.9110151518235229


In [17]:
mnb.fit(X_train,y_train)
y_pred2= mnb.predict(X_test)
print("accuracy_score",accuracy_score(y_test,y_pred2))
print("Confusion Matrix:\n",confusion_matrix(y_test,y_pred2))
print("weighted precision_score -" ,precision_score(y_test,y_pred2, average = 'weighted'))

accuracy_score 0.971830985915493
Confusion Matrix:
 [[ 94   0   1   0   1]
 [  0  66   2   0   0]
 [  3   0  79   1   0]
 [  0   0   0 109   0]
 [  1   1   1   1  66]]
weighted precision_score - 0.9719670591468543


In [18]:
bnb.fit(X_train,y_train)
y_pred3= bnb.predict(X_test)
print("accuracy_score",accuracy_score(y_test,y_pred3))
print("Confusion Matrix:\n",confusion_matrix(y_test,y_pred3))
print("weighted precision_score -" ,precision_score(y_test,y_pred3, average = 'weighted'))

accuracy_score 0.9624413145539906
Confusion Matrix:
 [[ 93   0   1   0   2]
 [  0  67   0   0   1]
 [  1   2  80   0   0]
 [  0   0   0 109   0]
 [  5   3   1   0  61]]
weighted precision_score - 0.9628027129476374


## Multinomial Naive Bayes gives the best accuracy, so we will proceed with it