In [1]:
import sklearn
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
df = pd.read_csv('../Data/CleanedData.csv')

In [3]:
df.head()

subject                                   transformed text
0        1  donald trump wish american happi new year leav...
1        1  hous intellig committe chairman devin nune go ...
2        1  friday reveal former milwauke sheriff david cl...
3        1  christma day donald trump announc would back w...
4        1  pope franci use annual christma day messag reb...

In [4]:
from sklearn.feature_extraction.text import CountVectorizer
cv= CountVectorizer(max_features=5000)

In [5]:
x= cv.fit_transform(df['transformed text']).toarray()
y= df['subject'].values

In [7]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size=0.2, random_state = 42)

In [8]:
random_forest = RandomForestClassifier()

# Define a parameter grid to search through
param_grid = {
    'n_estimators': [100, 300],                 # Number of trees in the forest
    'max_depth': [10, 30],                 # Maximum depth of the trees
    'min_samples_split': [ 5, 10],                # Minimum samples required to split an internal node
    'min_samples_leaf': [ 2, 4],                  # Minimum samples required to be at a leaf node
    'max_features': ['sqrt', 'log2', None]  # Number of features to consider at each split
}

# Create a GridSearchCV object with the model and parameter grid
grid_search = GridSearchCV(random_forest, param_grid, cv=2, scoring='accuracy', verbose = 4)

# Fit the grid search to your training data
grid_search.fit(x_train, y_train)

# Print the best hyperparameters and corresponding accuracy score
print("Best Hyperparameters:", grid_search.best_params_)
print("Best Accuracy Score:", grid_search.best_score_)

# Use the best estimator to make predictions on the test data
best_model = grid_search.best_estimator_
y_pred = best_model.predict(x_test)



Fitting 2 folds for each of 48 candidates, totalling 96 fits
[CV 1/2] END max_depth=10, max_features=sqrt, min_samples_leaf=2, min_samples_split=5, n_estimators=100;, score=0.715 total time=   7.3s
[CV 2/2] END max_depth=10, max_features=sqrt, min_samples_leaf=2, min_samples_split=5, n_estimators=100;, score=0.712 total time=   7.3s
[CV 1/2] END max_depth=10, max_features=sqrt, min_samples_leaf=2, min_samples_split=5, n_estimators=300;, score=0.711 total time=  21.0s
[CV 2/2] END max_depth=10, max_features=sqrt, min_samples_leaf=2, min_samples_split=5, n_estimators=300;, score=0.709 total time=  20.5s
[CV 1/2] END max_depth=10, max_features=sqrt, min_samples_leaf=2, min_samples_split=10, n_estimators=100;, score=0.712 total time=   7.1s
[CV 2/2] END max_depth=10, max_features=sqrt, min_samples_leaf=2, min_samples_split=10, n_estimators=100;, score=0.706 total time=   7.1s
[CV 1/2] END max_depth=10, max_features=sqrt, min_samples_leaf=2, min_samples_split=10, n_estimators=300;, score=0.

[CV 1/2] END max_depth=30, max_features=sqrt, min_samples_leaf=4, min_samples_split=10, n_estimators=100;, score=0.748 total time=  10.8s
[CV 2/2] END max_depth=30, max_features=sqrt, min_samples_leaf=4, min_samples_split=10, n_estimators=100;, score=0.754 total time=  10.8s
[CV 1/2] END max_depth=30, max_features=sqrt, min_samples_leaf=4, min_samples_split=10, n_estimators=300;, score=0.754 total time=  31.4s
[CV 2/2] END max_depth=30, max_features=sqrt, min_samples_leaf=4, min_samples_split=10, n_estimators=300;, score=0.758 total time=  31.8s
[CV 1/2] END max_depth=30, max_features=log2, min_samples_leaf=2, min_samples_split=5, n_estimators=100;, score=0.707 total time=   3.7s
[CV 2/2] END max_depth=30, max_features=log2, min_samples_leaf=2, min_samples_split=5, n_estimators=100;, score=0.712 total time=   3.7s
[CV 1/2] END max_depth=30, max_features=log2, min_samples_leaf=2, min_samples_split=5, n_estimators=300;, score=0.716 total time=  10.3s
[CV 2/2] END max_depth=30, max_featur

In [9]:
# Evaluate the model's performance on the test data
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

print("Test Accuracy:", accuracy)
print("Confusion Matrix:\n", conf_matrix)
print("Classification Report:\n", class_report)


Test Accuracy: 0.768927536231884
Confusion Matrix:
 [[   0   27    0    0  255    5]
 [   0 1677    0    0  197    2]
 [   0   24   78    0   60    3]
 [   0  100    0    0  723   12]
 [   1  230    0   61 3069  114]
 [   0    0    0    0  179 1808]]
Classification Report:
               precision    recall  f1-score   support

           0       0.00      0.00      0.00       287
           1       0.81      0.89      0.85      1876
           2       1.00      0.47      0.64       165
           3       0.00      0.00      0.00       835
           4       0.68      0.88      0.77      3475
           5       0.93      0.91      0.92      1987

    accuracy                           0.77      8625
   macro avg       0.57      0.53      0.53      8625
weighted avg       0.69      0.77      0.72      8625

